# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'jsrequire/version'

Gem::Specification.new do |spec|
  spec.name          = "jsrequire"
  spec.version       = JsRequire::VERSION
  spec.authors       = ["Michael Siebert", "Lars Kluge"]
  spec.email         = ["michael.siebert@samedi.de"]
  spec.description   = %q{Organizes requirements of assets in JavaScript files, resolved dependencies of js files and helps include depending css files.}
  spec.summary       = %q{Organizes requirements of assets in JavaScript files, resolved dependencies of js files and helps include depending css files.}
  spec.homepage      = ""
  spec.license       = "private"

  spec.files         = `git ls-files`.split($/)
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ["lib"]

  spec.add_development_dependency "bundler", "~> 1.3"
  spec.add_development_dependency "rake"
end

